config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #get 'home/index'
  root 'home#index'
  get 'home/about'

  get 'stocks/historical_chart/:stock', :to => 'stocks#historical_chart'
  get 'stocks/stock_news/:stock', :to => 'stocks#stock_news'

  get '/search', :to => 'home#search', as: :stock_search

  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord

  belongs_to :user

  before_save :uppercase_ticker

  def uppercase_ticker
    ticker.upcase!
  end

  validates :ticker, :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 1 }


  def self.find_most_popular
    popularity = {}
    Stock.find_each do |stock|
      if popularity[stock.ticker.to_sym]
        popularity[stock.ticker.to_sym] += 1
      else
        popularity[stock.ticker.to_sym] = 1
      end
    end
    return popularity
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  require 'rest-client'
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
    @new_stock = Stock.new
    @industry_breakdown = PortfolioCache.industry_breakdown_for_highcharts(current_user)
    @portfolio_cache = portfolio
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
  end

  def historical_chart
    historical = RestClient.get "https://api.iextrading.com/1.0/stock/#{params[:stock]}/chart/5y"

    respond_to do |format|
      format.json { render json: historical, status: :ok }
      format.html
    end
  end

  def stock_news
    news = RestClient.get "https://api.iextrading.com/1.0/stock/#{params[:stock]}/news/last/5"

    respond_to do |format|
      format.json { render json: news, status: :ok }
      format.html
    end
  end




  # GET /stocks/new
  def new
    @stock = Stock.new
    @portfolio = nil
  end

  # GET /stocks/1/edit
  def edit
    @portfolio = nil
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
    @portfolio = nil
  end

  def search

    if params[:id] == ""
      @nothing = "Please enter a symbol"
    elsif

      if params[:id]
        begin
          @stock = StockQuote::Stock.quote(params[:id])
          @stock_json = StockQuote::Stock.json_quote(params[:id])
        rescue StandardError
          @error = "That stock symbol is not valid"
        end

      end
    end

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def portfolio
      @portfolio ||= PortfolioCache.new current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id, :quantity)
    end

    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "You are not authorized to edit this stock" if @ticker.nil?
    end


end

app/helpers/stocks_helper.rb
module StocksHelper

  def display_most_popular
    most_popular = Stock.find_most_popular.sort_by {|_key, value| value}.reverse.first(5)
    content_tag :ul do
      most_popular.collect { |stock| concat(content_tag(:li, stock[0].to_s + ' : ' + stock[1].to_s)) }
    end
  end

  def display_similar_portfolio_filtering
    recommendations = PortfolioCache.similar_portfolio_filtering(current_user).sort_by {|_key, value| value}.reverse.first(5)
    content_tag :ul do
      recommendations.collect { |stock| concat(content_tag(:li, stock[0].to_s + ' : ' + stock[1].to_s)) }
    end
  end

  def display_similar_portfolios
    similar_portfolios = PortfolioCache.find_portfolio_similarity_scores(current_user).sort_by {|_key, value| value}.reverse.first(5)
    content_tag :ul do
      similar_portfolios.collect { |portfolio| concat(content_tag(:li, User.where(:id => portfolio[0]).pluck(:username)[0] + ' : ' + portfolio[1].to_s)) }
    end
  end

end

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true, url: stocks_path, method: 'post') do |form| %>

  <div class="form_group margin-bottom-20">
    <%= form.text_field :ticker, id: :stock_ticker, class: 'form-control', style: "text-transform: uppercase", placeholder: 'Ticker' %>
  </div>

  <div class="form_group margin-bottom-20">
    <%= form.number_field :quantity, id: :stock_quantity, class: 'form-control', placeholder: 'Quantity' %>
  </div>

  <div class="form_group margin-bottom-20">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions text-center">
    <%= form.submit "ADD TO PORTFOLIO", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/stocks/_portfolio_chart.html.erb
<div id="portfolio"></div>

<%= content_tag :span, '', class: 'js-stocks', data: { stocks: @industry_breakdown } %>

app/views/stocks/_stockInfo.html.erb
<ul>
  <li>
    <h4 class="text-center"><i class="fa fa-line-chart" aria-hidden="true"></i>  STOCK INFO</h4>
    <button class="close_infobox" onclick="document.getElementById('stockInfoClose').style.display='none'" ><i class="fa fa-times" aria-hidden="true"></i></button>
  </li>
  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Company Name</span>
    </div>
    <div class="col-md-8">
      <%= @stock.name %> - <%= @stock.symbol %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Current Ask</span>
    </div>
    <div class="col-md-8">
      <%= @stock.l %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> EPS</span>
    </div>
    <div class="col-md-8">
      <%= @stock.eps %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> P/E Ratio</span>
    </div>
    <div class="col-md-8">
      <%= @stock.pe %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Market Cap</span>
    </div>
    <div class="col-md-8">
      <%= @stock.mc %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Open</span>
    </div>
    <div class="col-md-8">
      <%= @stock.op %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Day's Range</span>
    </div>
    <div class="col-md-8">
      <%= @stock.lo %> - <%@stock.hi %>
    </div>
  </li>
  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Year High</span>
    </div>
    <div class="col-md-8">
      <%= @stock.hi52 %>
    </div>
  </li>
  <li>
    <div class="col-md-4">
      <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Year Low</span>
    </div>
    <div class="col-md-8">
      <%= @stock.lo52 %>
    </div>
  </li>

  <li>
    <div class="col-md-4">
       <span><i class="fa fa-angle-double-right" aria-hidden="true"></i> Website</span>
    </div>
    <div class="col-md-8">
      <%= link_to @stock.summary[0]['url'], @stock.summary[0]['url'] %>
    </div>
  </li>
</ul>

app/views/stocks/edit.html.erb
<%= render "home/navbar" %>

<main>
  <div class="col-md-6 col-md-offset-3">
    <div class="box">
      <h4>Editing Stock</h4>
      <p class="margin-bottom-20">
        Change the stock name and quantity
      </p>
      <%= render 'form', stock: @stock %>

      <div class="editing_links text-center margin-bottom-20 margin-top-20">
        <%= link_to @stock, class: "btn editing_links" do %>
          <i class="fa fa-eye" aria-hidden="true"></i>
          Show
        <% end %>
        <%= link_to stocks_path, class: "btn editing_links" do %>
          <i class="fa fa-reply" aria-hidden="true"></i>
          Back
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/stocks/index.html.erb
<%= render "home/navbar" %>

  <main>

    <div class="col-md-6 ">
      <div class="box">
        <!-- <h4>portfolio chart</h4> -->
        <%= render 'portfolio_chart', stocks: @stocks, stock_quote: StockQuote::Stock %>

      <div id="portfolio"></div>
      </div>
    </div>

    <div class="col-md-6 ">
      <div class="box">
        <h4>ADD NEW STOCK</h4>
        <%= render 'form', stock: @new_stock %>
      </div>

      <div class="col-md-12 padding-0">
        <div class="box">
          <h4>QUOTE LOOKUP</h4>
          <div class="user_profile search_box_area dashboard_search">
            <%= form_tag stock_search_path, :method => "GET" do %>
              <%= text_field_tag 'id', nil, placeholder: "Enter Companyname, Ticker or Symbol", size: 50 %>
              <%= button_to do %>
                 <i class="fa fa-search" aria-hidden="true"></i>
              <% end %>
            <% end %>

            <% if @stock %>
              <div class="col-md-8 col-md-offset-2 stock_info_box">
                <%= render '/stocks/stockInfo' %>
              </div>
            <% elsif @nothing %>
              <%= @nothing %>
            <% end %>

            <% if @error %>
             <%= @error %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12 ">
      <div class="box">
        <h4>PORTFOLIO Details</h4>
        <table class="table table-striped table-bordered portfolio_table bg-primary">
          <thead>
            <tr>
              <th>Company Name</th>
              <th>Ticker</th>
              <th>Current Price</th>
              <th>Company Worth</th>
              <th>Quantity</th>
              <th>Sector</th>
              <th>Total Value</th>
              <th>Options</th>
            </tr>
          </thead>

          <tbody>
            <% @portfolio_cache = PortfolioCache.build_portfolio_cache(current_user) %>
            <% @portfolio_cache.each do |stock| %>
                <% begin %>
                  <tr class="dashboard_table">
                    <td class="no_padding_row"><%= link_to stock[:name], stock_path(stock[:id]) %></td>
                    <td class="no_padding_row"><%= link_to stock[:ticker], stock_path(stock[:id]) %></td>
                    <td class="padding_row"><%= stock[:last_price] %></td>
                    <td class="padding_row"><%= stock[:market_cap] %></td>
                    <td class="padding_row"><%= stock[:quantity] %></td>
                    <td class="padding_row"><%= stock[:sector] %></td>
                    <td class="padding_row"><%= stock[:total_value] %></td>
                    <td class="no_padding_row">
                        <%= link_to edit_stock_path(stock[:id]), class: 'icons' do%>
                          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        <% end %>
                        <%= link_to stock_path(stock[:id]), method: :delete, class: 'icons' do %>
                          <i class="fa fa-trash" aria-hidden="true"></i>
                        <% end %>
                    </td>
                  </tr>
                <% rescue StandardError => e %>
                <%= e.message %>
                  <tr>
                    <td><%= link_to "Error", stock_path(stock[:id]) %></td>
                    <td><%= "Error" %></td>
                    <td><%= "Error" %></td>
                    <td><%= "Error" %></td>
                  </tr>
                  <% next %>
                <% end %>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>

  </main>
</div>

app/views/stocks/new.html.erb
<%= render "home/navbar" %>

<main>
  <div class="col-md-6 col-md-offset-3">
    <div class="box">
      <h4>New Stock</h4>
      <p class="margin-bottom-20">
        Choose a stock and quantity to add it to your portfolio
      </p>
      <%= render 'form', stock: @stock %>

      <div class="editing_links text-center margin-bottom-20 margin-top-20">
        <%= link_to stocks_path, class: "btn editing_links" do %>
          <i class="fa fa-reply" aria-hidden="true"></i>
          Back
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/stocks/search.html.erb
<%= render 'stockinfo' %>

app/views/stocks/show.html.erb
<main>
  <div class="col-md-12 stock_info">
    <div class="box">
      <% begin %>
        <% @stock_quote = StockQuote::Stock.quote(@stock.ticker) %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="row">
              <div class="col-md-7 stock_edit_buttons">
                <h3 class="panel-title"><%= @stock_quote.name %> - <%= @stock_quote.symbol %>  </h3>
                <h5><%= @stock.quantity %> Shares</h5>
              </div>

              <div class="col-md-5">

                <%= link_to edit_stock_path(@stock), class: 'home_button' do%>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  Edit
                <% end %>
                <%= link_to stock_path(@stock), method: :delete, class: 'home_button' do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                  Remove Stock
                <% end %>
                <%= link_to stocks_path, class: 'home_button' do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>
                  Back
                <% end %>
              </div>
            </div>
          </div>

          <div class="panel-body">
            <div class="col-md-5">
              <h1>$<%= @stock_quote.l %></h1>
              <% if @stock_quote.c.to_f.positive? %>
                <div class="col-md-4">
                  <h4 class="green"><i class="fa fa-angle-double-up" aria-hidden="true"></i>  <%= @stock_quote.c %> $</h4>
                </div>
                <div class="col-md-8">
                  <h4 class="green"><i class="fa fa-angle-double-up" aria-hidden="true"></i> <%= @stock_quote.cp %>%</h4>
                </div>
              <% else %>
                 <div class="col-md-4">
                  <h4 class="red"><i class="fa fa-angle-double-down" aria-hidden="true"></i> <%= @stock_quote.c %> $</h4>
                </div>
                <div class="col-md-8">
                  <h4 class="red"><i class="fa fa-angle-double-down" aria-hidden="true"></i> <%= @stock_quote.cp %>%</h4>
                </div>
              <% end %>

              <ul class="stock_detail_table">
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  EPS</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.eps %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  P/E Ratio</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.pe %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Market Cap</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.mc %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Open</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.op %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Day's Range</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.lo %> - <%= @stock_quote.hi %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year High</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.hi52 %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year Low</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.lo52 %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Sector</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.sname %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Industry</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock_quote.iname %>
                  </div>
                </li>
              </ul>

            </div>
            <div class="col-md-7">
              <p align="justify" class="stock_info_data"><%= @stock_quote.summary[0]["overview"] %></p>

              <div class="related_stocks_box">
                <div class="col-md-3 padding-0">
                  <h5>Related stocks:</h5>
                </div>

                <div class="col-md-9 related_stocks padding-0">
                  <ul>
                    <li><%= @stock_quote.related[1]["t"] %></li>
                    <li><%= @stock_quote.related[2]["t"] %></li>
                    <li><%= @stock_quote.related[3]["t"] %></li>
                    <li><%= @stock_quote.related[4]["t"] %></li>
                    <li><%= @stock_quote.related[5]["t"] %></li>
                  </ul>
                </div>
              </div>

            </div>
            <% rescue StandardError %>
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="col-md-5">

              <h1>$<%= @stock.ticker %></h1>

              <ul>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  EPS</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>

                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  P/E Ratio</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Market Cap</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Open</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Day's Range</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year High</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year Low</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Sector</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Industry</span>
                  </div>
                  <div class="col-md-7">
                    <%= "N/A" %>
                  </div>
                </li>
              </ul>

            </div>

            <% end %>

        </div>

      </div>

    </div>
  </div>

  <div class="col-md-8 stock_info">
    <div class="box">
      <!-- <h4>Stock History</h4> -->
      <div id="container" class="historical_chart_box"></div>
    </div>
  </div>

  <div class="col-md-4 stock_info stock_info_news">
    <div class="box">
      <h4>News</h4>
        <ul id="news">

        </ul>

    </div>
  </div>
</main>

<script>
  var stockTicker = "<%= @stock.ticker %>";
</script>