config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #get 'home/index'
  root 'home#index'
  get 'home/about'

  get 'stocks/historical_chart/:stock', :to => 'stocks#historical_chart'
  get 'stocks/stock_news/:stock', :to => 'stocks#stock_news'

  get '/search', :to => 'home#search', as: :stock_search

  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_action :verify_authenticity_token, only: [:index]


  def index

  end

   def search

    if params[:id] == ""
      @nothing = "Please enter a symbol"
    elsif

      if params[:id]
        begin
          @stock = StockQuote::Stock.quote(params[:id])
          @stock_json = StockQuote::Stock.json_quote(params[:id])
        rescue StandardError
          @error = "That stock symbol is not valid"
        end

      end
    end
  end

  def about

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_homeNavbar.html.erb
<header class="home_two">

  <nav class="navbar navbar-default">

    <% unless user_signed_in? %>

    <div class="user_profile col-3">

    <button type="button" class="home_button">
      <%= link_to root_path do %>
      <i class="fa fa-home" aria-hidden="true"></i>
      Home
      <% end %>
    </button>

    <!-- Register Login -->

    <button type="button" class="home_button" data-toggle="modal" data-target="#registerModal"><i class="fa fa-address-book" aria-hidden="true"></i> Register</button>

    <!-- Registration modal form -->
    <%= render 'signupForm' %>


    <button type="button" class="home_button" data-toggle="modal" data-target="#loginModal"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</button>

    <!-- Login form -->

    <%= render 'loginForm' %>

    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <span class="name">Hi <%= current_user.first_name %></span>
          <span class="location"><%= current_user.country %></span>
        </li>
        <li>
          <%= link_to root_path, class: 'home_button' do %>
          <i class="fa fa-home" aria-hidden="true"></i>
          Home
          <% end %>
        </li>
        <li>
          <%= link_to stocks_path, class: 'home_button' do %>
          <i class="fa fa-briefcase" aria-hidden="true"></i>
          Portfolio
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, class: 'home_button',method: :delete do%>
          <i class='fa fa-sign-out' aria-hidden='true'></i>
          Logout
          <% end %>
        </li>
      </ul>
     <% end %>
    </div>
  </nav>
</header>

app/views/home/_loginForm.html.erb
    <!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-center" id="loginModalLabel">Welcome to Portfol.io</h3>
        <p class="text-center">Please enter your details</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="fa fa-times" aria-hidden="true"></i>
        </button>
      </div>
      <div class="modal-body">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Please enter your email address' %>
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Please enter the password' %>
                <i class="fa fa-lock" aria-hidden="true"></i>
              </div>

              <% if devise_mapping.rememberable? -%>
                <div class="form-group">
                  <%= f.check_box :remember_me %> <%= f.label :remember_me %>

                </div>
              <% end -%>

              <div class="actions">
                <%= f.submit "LOG IN", class: "btn btn-primary"%>
              </div>
            <% end %>
          </div>

          <div class="panel-footer text-center">
            <%= link_to user_facebook_omniauth_authorize_path, class: 'fb_login' do %>
              <i class="fa fa-facebook" aria-hidden="true"></i>Login with Facebook
            <% end %>
          </div>
          <!-- <%#= render "devise/shared/links" %> -->
        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<!-- Sidebar Menu -->
  <div class="col-md-2 padding-0">

    <aside>
      <nav>
        <div class="logo_section">
          <%= link_to root_path do %>
            <%= image_tag ('logo.png') %>
            <hgroup>
              <h1>Portfol.io</h1>
              <h5>Make More Money</h5>
            </hgroup>
          <% end %>
        </div>
        <% if user_signed_in? %>
        <ul>
          <li>
            <h5 class="recommend_header">Most popular</h5>

              <%= display_most_popular %>

          </li>
          <li>
            <h5 class="recommend_header">Similar portfolios</h5>

              <%= display_similar_portfolios %>

          </li>
          <li>
            <h5 class="recommend_header">Stocks from similar portfolios</h5>

              <%= display_similar_portfolio_filtering %>

          </li>
        </ul>
        <% end %>
      </nav>
    </aside>

  </div>

<!-- Main NAv -->

<div class="col-md-10 padding-0 side_box_model">
  <nav class="navbar navbar-default dashbard_navbar">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav"></ul>
        <ul class="nav navbar-nav navbar-right">



        </ul>
      </div>


      <% if user_signed_in? %>

      <div class="user_profile col-md-11">

        <ul class="nav navbar-nav navbar-right dashboard_home_nav">
          <li>
            <span class="name">Hi <%= current_user.first_name %></span>
            <span class="location"><%= current_user.country %></span>
          </li>

          <!-- <li>
            <%#= link_to new_stock_path do %>
              <i class="fa fa-pie-chart" aria-hidden="true"></i>
              Add Stock
            <%# end %>
          </li>

          <li>
            <%#= link_to stocks_path, class: 'home_button' do %>
            <i class="fa fa-briefcase" aria-hidden="true"></i>
            Portfolio
            <%# end %>
          </li> -->

          <li>
            <%= link_to destroy_user_session_path, method: :delete do%>
            <i class='fa fa-sign-out' aria-hidden='true'></i>
            Logout
            <% end %>
          </li>

        </ul>
        </div>
       <% else %>
       <div class="user_profile col-md-11">
        <ul class="nav navbar-nav navbar-right dashboard_home_nav">
          <li>
            <%= link_to new_user_registration_path, class: 'home_button' do %>
            <i class="fa fa-address-book" aria-hidden="true"></i>
            Register
            <% end %>
          </li>

          <li>
            <%= link_to new_user_session_path, class: 'home_button' do%>
            <i class="fa fa-sign-in" aria-hidden="true"></i>
            Log In
            <% end %>
          </li>
        </ul>
      </div>
       <% end %>


      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

app/views/home/_signupForm.html.erb
<!-- Modal -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-center" id="loginModalLabel">Welcome to Portfol.io</h3>
        <p class="text-center">Please enter your details</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="fa fa-times" aria-hidden="true"></i>
        </button>
      </div>
      <div class="modal-body">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>

              <div class="form-group">
                <%= f.text_field :first_name, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your first name' %>
                <i class="fa fa-user-plus" aria-hidden="true"></i>

              </div>

              <div class="form-group">
                <%= f.text_field :last_name, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your last name' %>
                <i class="fa fa-user-plus" aria-hidden="true"></i>

              </div>

              <div class="form-group">
                <%= f.text_field :username, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your username' %>
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Please enter your email address' %>
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.number_field :age, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your age' %>
                <i class="fa fa-birthday-cake" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.text_field :country, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your country' %>
                <i class="fa fa-map-marker" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.number_field :annual_income, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your annual income' %>
                <i class="fa fa-money" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.text_field :occupation, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your occupation' %>
                <i class="fa fa-briefcase" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %>
                <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Please enter your password' %>
                <i class="fa fa-key" aria-hidden="true"></i>
              </div>

              <div class="form-group">
                <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Confirm your password' %>
                <i class="fa fa-key" aria-hidden="true"></i>
              </div>



              <div class="actions">
                <%= f.submit "REGISTER", class: "btn btn-primary"%>
              </div>
            <% end %>

          </div>
        </div>
        <!-- <%#= render "devise/shared/links" %> -->
      </div>

    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>This is my first rails app</p>

app/views/home/index.html.erb
<div class="row home_bg">
  <h1>
    <%= image_tag ('logo.png') %> Portfol.io
    <span>Make More Money</span>
  </h1>

<!-- slider -->

  <div class="col-md-6 padding-0 carousel_box">

    <div id="carousel" class="carousel slide" data-ride="carousel">
      <!-- Menu -->
      <ol class="carousel-indicators">
          <li data-target="#carousel" data-slide-to="0" class="active"></li>
          <li data-target="#carousel" data-slide-to="1"></li>
          <li data-target="#carousel" data-slide-to="2"></li>
      </ol>

      <!-- Items -->
      <div class="carousel-inner">

          <div class="item active">
              <%= image_tag ("home5.jpg") %>
                <div class="carousel-caption">
                  <h2>VIEW</h2>
                  <p>Analyze stock details</p>
                </div>
          </div>
          <div class="item">
              <%= image_tag ("home1.jpg") %>
              <div class="carousel-caption">
                <h2>BUILD</h2>
                <p>Build your own personal portfolio</p>
              </div>
          </div>
          <div class="item">
              <%= image_tag ("slide1.jpg") %>
              <div class="carousel-caption">
                <h2>DIVERSIFY</h2>
                <p>Get recommendations to improve your portfolio</p>
              </div>
          </div>
      </div>
     <!--  <a href="#carousel" class="left carousel-control" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a href="#carousel" class="right carousel-control" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
      </a> -->
    </div>
  </div>

  <div class="col-md-6 col-xs-12 info_section">
      <%= render "homeNavbar" %>

    <% unless user_signed_in? %>
    <!-- Search -->
    <div class="col-md-12 col-xs-12 search_box_area after_login_page">

      <h2 class="text-center">VIEW . BUILD . DIVERSIFY</h2>

     <%= form_tag stock_search_path, :method => "GET" do %>
        <%= text_field_tag 'id', nil, placeholder: "Enter Companyname, Ticker or Symbol", size: 50 %>
        <%= button_to do %>
           <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
    <!-- stock info -->

    <% if @stock %>
      <div class="col-md-10 col-md-offset-1 col-xs-12 stock_info_box" id="stockInfoClose">

        <%= render 'stockInfo' %>
      </div>
    <% elsif @nothing %>
      <%= @nothing %>
    <% end %>

    <% if @error %>
      <%= @error %>
    <% end %>

    <div class="col-md-12 col-xs-12 footer_only_homepage">
      <p>All Right Reserved Protfol.io 2017</p>
    </div>
    <% else %>
      <div class="col-md-6 col-md-offset-6 col-xs-12 search_box_area after_login_page">
        <h2 class="text-center">VIEW . BUILD . DIVERSIFY</h2>
        <%= form_tag stock_search_path, :method => "GET" do %>
        <%= text_field_tag 'id', nil, placeholder: "Enter Companyname, Ticker or Symbol", size: 50 %>
        <%= button_to do %>
           <i class="fa fa-search" aria-hidden="true"></i>
        <% end %>
      <% end %>

        <div class="text-center portfolio_button">
          <%#= link_to stocks_path, class: 'home_button view_portfolio' do %>
            <!-- <i class="fa fa-pie-chart" aria-hidden="true"></i>
            VIEW PORTFOLIO -->
          <%# end %>
        </div>
      </div>

      <!-- stock info -->

        <% if @stock %>
          <div class="col-md-5 stock_info_box homepage_login_search" id="stockInfoClose">
            <%= render 'stockInfo' %>
          </div>
        <% elsif @nothing %>
          <%= @nothing %>
        <% end %>

        <% if @error %>
          <%= @error %>
        <% end %>

       <div class="col-md-6 col-md-offset-6 col-xs-12">
          <div class="col-md-12 footer_only_homepage">
            <p>All Right Reserved Porfol.io 2017</p>
          </div>
        </div>
    <% end %>




  </div>

</div><!-- row end -->

app/views/home/search.html.erb
  <div class="row home_bg">
    <h1>
      <%= image_tag ('logo.png') %> Portfol.io
      <span>Make More Money</span>
    </h1>
  </div>


 <%= render "homeNavbar" %>

<main>
  <div class="col-md-12 stock_info">
    <div class="box">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="row">
              <div class="col-md-7 stock_edit_buttons">
                <h3 class="panel-title"><%= @stock.name %> - <%= @stock.symbol %>  </h3>
              </div>

            </div>
          </div>

          <div class="panel-body">
            <div class="col-md-5">
              <h1>$<%= @stock.l %></h1>
              <% if @stock.c.to_f.positive? %>
                <div class="col-md-4">
                  <h4 class="green"><i class="fa fa-angle-double-up" aria-hidden="true"></i>  <%= @stock.c %> $</h4>
                </div>
                <div class="col-md-8">
                  <h4 class="green"><i class="fa fa-angle-double-up" aria-hidden="true"></i> <%= @stock.cp %>%</h4>
                </div>
              <% else %>
                 <div class="col-md-4">
                  <h4 class="red"><i class="fa fa-angle-double-down" aria-hidden="true"></i> <%= @stock.c %> $</h4>
                </div>
                <div class="col-md-8">
                  <h4 class="red"><i class="fa fa-angle-double-down" aria-hidden="true"></i> <%= @stock.cp %>%</h4>
                </div>
              <% end %>

              <ul class="stock_detail_table">
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  EPS</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.eps %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  P/E Ratio</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.pe %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Market Cap</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.mc %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Open</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.op %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Day's Range</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.lo %> - <%= @stock.hi %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year High</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.hi52 %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Year Low</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.lo52 %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Sector</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.sname %>
                  </div>
                </li>
                <li>
                  <div class="col-md-5">
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i>  Industry</span>
                  </div>
                  <div class="col-md-7">
                    <%= @stock.iname %>
                  </div>
                </li>
              </ul>

            </div>
            <div class="col-md-7">
              <p align="justify" class="stock_info_data"><%= @stock.summary[0]["overview"] %></p>

              <div class="related_stocks_box">
                <div class="col-md-3 padding-0">
                  <h5>Related stocks:</h5>
                </div>

                <div class="col-md-9 related_stocks padding-0">
                  <ul>
                    <li><%= @stock.related[1]["t"] %></li>
                    <li><%= @stock.related[2]["t"] %></li>
                    <li><%= @stock.related[3]["t"] %></li>
                    <li><%= @stock.related[4]["t"] %></li>
                    <li><%= @stock.related[5]["t"] %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

  <div class="col-md-8 stock_info">
    <div class="box">
      <div id="container"></div>
    </div>
  </div>

  <div class="col-md-4 stock_info stock_info_news">
    <div class="box">
      <h4>News</h4>
        <ul id="news">

        </ul>

    </div>
  </div>
</main>
<script>
  var stockTicker = "<%= @stock.symbol %>";
</script>